org: amsross
app: cloudcast
service: cloudcast

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, "dev"}
  environment:
    SERVICE: ${self:service}
    STAGE: ${self:provider.stage}
    REGION: ${opt:region, "us-east-1"}
    LATITUDE: ${env:LATITUDE}
    LONGITUDE: ${env:LONGITUDE}
    OPENWEATHER_API_KEY: ${env:OPENWEATHER_API_KEY}
    PHONE_NUMBER: ${opt:PHONE_NUMBER}

  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

functions:
  cron:
    handler: handler.cron
    events:
      - schedule:
        name: check-the-weather
        description: "check the weather"
        rate: cron(0 20 * * ? *)
