name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies -- ${{ matrix.node-version }}
      run: npm ci
      uses: actions/checkout@v2
    - name: build artifacts -- ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      run: npm run build --if-present
